site_name: ez-address-parser
nav:
  - Home: index.md
theme:
  name: material
  favicon: https://cdn2.iconfinder.com/data/icons/seo-and-website/100/SEO_search_word-512.png
  logo: https://cdn2.iconfinder.com/data/icons/seo-and-website/100/SEO_search_word-512.png
  font:
    text: Roboto
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - header.autohide
    - content.code.copy
repo_name: ez-address-parser
repo_url: https://github.com/zehengl/ez-address-parser
plugins:
  - search
  - tags
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zehengl
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/zehengl
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
