target = "latest"
no_ssl_verify = false
ignore_warning = false
show_full_path = false
upgrade = false
no_color = false
no_recursive = false
ignore_additional_labels = false
filter = []
ignores = []
default_venv = ".venv"
interactive = false
txt = false
init = false
path = "requirements-dev.txt"
extra = []
pre = false
